---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 5m0s
  # dependsOn:
  #   - name: prometheus-operator-crd
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/minikube/sync-code/kyverno/test
  prune: true
  wait: true
  timeout: 20m0s
