---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 5m
  releaseName: kyverno
  targetNamespace: kyverno
  storageNamespace: kyverno
  chart:
    spec:
      chart: kyverno
      version: '3.0.1'
      sourceRef:
        kind: HelmRepository
        name: kyverno-repo
        namespace: kyverno
  # Uncomment for production HA
  values:
    config:
      value:
        webhooks:
          - namespaceSelector:
              matchExpressions:
                - key: kubernetes.io/metadata.name
                  operator: NotIn
                  values:
                    - kube-system
                    - kyverno
    features:
      policyExceptions:
        enabled: true
      logging:
        format: json
    admissionController:
      replicas: 3
      container:
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 256Mi
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: prometheus
    backgroundController:
      replicas: 2
      resources:
        limits:
          memory: 512Mi
        requests:
          memory: 256Mi
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: prometheus
    cleanupController:
      replicas: 2
      resources:
        limits:
          memory: 512Mi
        requests:
          memory: 256Mi
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: prometheus
    reportsController:
      replicas: 2
      resources:
        limits:
          memory: 512Mi
        requests:
          memory: 256Mi
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: prometheus
