---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kafka
  namespace: flux-system
spec:
  interval: 5m
  releaseName: kafka
  targetNamespace: default
  storageNamespace: default
  chart:
    spec:
      chart: kafka
      version: '20.0.6'  # kafka version 3.3.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  valuesFrom:
  - kind: ConfigMap
    name: kafka-values
