---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rabbitmq-operator
  namespace: flux-system   # we put HelmRelease resources into flux namespace to make use of secretRef with Git credentials
spec:
  interval: 1h0m0s
  releaseName: rabbitmq-operator
  targetNamespace: rabbitmq-system   # the namespace where Helm chart gets deployed
  storageNamespace: rabbitmq-system
  chart:
    spec:
      chart: rabbitmq-cluster-operator
      version: 2.7.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    msgTopologyOperator:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
