---
# Source: https://github.com/rabbitmq/cluster-operator/tree/main/docs/examples/production-ready
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: d005
spec:
  image: 'docker.io/bitnami/rabbitmq:3.10.7-debian-11-r3'
  # service:
  #   annotations:
  #     cloud.google.com/neg: '{"exposed_ports": {"5672":{"name": "rabbitmq-tls"}}}'
  #     controller.autoneg.dev/neg: '{"backend_services":{"5672":[{"name":"d005-tcp-backend-service","max_connections_per_endpoint":10000}]}}'
  replicas: 1
  terminationGracePeriodSeconds: 5  # 604800 default
  resources:
    requests:
      cpu: 0.1
      memory: 128Mi 
    limits:
      cpu: 0.1
      memory: 128Mi
  rabbitmq:
    additionalConfig: |
      cluster_partition_handling = autoheal
      vm_memory_high_watermark_paging_ratio = 0.99
      disk_free_limit.relative = 1.0
      collect_statistics_interval = 10000
      log.file.level = info
      prometheus.return_per_object_metrics = true
  persistence:
    storageClassName: ssd
    storage: "2Gi"