apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-ui-values
  namespace: flux-system
data:
  values.yaml: |

    ingress:
        hosts:
          - host: podinfo.production
            paths:
              - path: /
                pathType: ImplementationSpecific