---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: repositories
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
    path: ./infrastructure/repositories
    prune: false
