---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: shared-resources
  namespace: flux-system
resources:
  - ../../../infrastructure/git-repos
  - ../../../infrastructure/controllers/weave
