---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kafka-ui-configs
  namespace: flux-system
spec:
  interval: 5m
  path: "./clusters/minikube/sync-code/kafka/kafka-ui/configs"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kafka-ui
  namespace: flux-system
spec:
  dependsOn:
    - name: kafka-ui-configs
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/third-parties/kafka-ui
  prune: false
  interval: 10m0s
  targetNamespace: kafka
