---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kafka
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/third-parties/kafka
  prune: true
  wait: true
  timeout: 20m
  retryInterval: 5m
  patches:
    - patch: |

        - op: replace
          path: /spec/targetNamespace
          value: "kafka"
        - op: replace
          path: /spec/storageNamespace
          value: "kafka"
      target:
        kind: HelmRelease
        name: kafka
